version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: ~/repo
    steps:
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - checkout

      - setup_remote_docker

      # run tests!
      - run:
          name: Build image
          command: |
            set -x
            docker-compose build

      # run tests!
      - run:
          name: Run tests
          command: |
            set -x
            docker-compose run --rm --service-ports web pytest
